In [1]:
import pandas as pd
import numpy as np

In [2]:
data = [
    [10.1, 'M', 'green', 'class1'],
    [13.5, 'L', 'red', 'class2'],
    [15.3, 'XL', 'blue', 'class1'],
    [11.3, 'M', 'red', 'class1'],
    [13.2, 'L', 'blue', 'class2']]

In [3]:
df = pd.DataFrame(data, columns=['price', 'size', 'color', 'y'])
display(df)

price size  color       y
0   10.1    M  green  class1
1   13.5    L    red  class2
2   15.3   XL   blue  class1
3   11.3    M    red  class1
4   13.2    L   blue  class2

In [4]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
enc = OrdinalEncoder(categories=[['M', 'L', 'XL'], ['green', 'red', 'blue']], dtype=np.int16)

In [22]:
enc.fit(df[['size', 'color']])

OrdinalEncoder(categories=[['M', 'L', 'XL'], ['green', 'red', 'blue']],
               dtype=<class 'numpy.int16'>)

In [23]:
enc.categories_

[array(['M', 'L', 'XL'], dtype=object),
 array(['green', 'red', 'blue'], dtype=object)]

In [19]:
df

price size  color       y
0   10.1    M  green  class1
1   13.5    L    red  class2
2   15.3   XL   blue  class1
3   11.3    M    red  class1
4   13.2    L   blue  class2

In [24]:
size_enc = enc.transform(df[['size', 'color']])
print(size_enc)

[[0 0]
 [1 1]
 [2 2]
 [0 1]
 [1 2]]


In [25]:
df2 = df.copy()
df2[['size','color']] = size_enc

In [26]:
df2

price  size  color       y
0   10.1     0      0  class1
1   13.5     1      1  class2
2   15.3     2      2  class1
3   11.3     0      1  class1
4   13.2     1      2  class2

In [15]:
enc.inverse_transform(size_enc)

array([['M'],
       ['L'],
       ['XL'],
       ['M'],
       ['L']], dtype=object)

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder(categories=[['green','red', 'blue']], dtype=np.int16)

In [29]:
ohe.fit(df[['color']])

OneHotEncoder(categories=[['green', 'red', 'blue']],
              dtype=<class 'numpy.int16'>)

In [31]:
color_ohe = ohe.transform(df[['color']])

In [33]:
df

price size  color       y
0   10.1    M  green  class1
1   13.5    L    red  class2
2   15.3   XL   blue  class1
3   11.3    M    red  class1
4   13.2    L   blue  class2

In [32]:
color_ohe.toarray()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [41]:
cols = ohe.categories_[0]
temp = pd.DataFrame(color_ohe.toarray(), columns=cols)
display(temp)

green  red  blue
0      1    0     0
1      0    1     0
2      0    0     1
3      0    1     0
4      0    0     1

In [48]:
df3 = pd.concat([df2, temp], axis=1)
df3 = df3.drop(columns=['color'])
df3 = df3[['price', 'size', 'green', 'red', 'blue', 'y']]
display(df3)

price  size  green  red  blue       y
0   10.1     0      1    0     0  class1
1   13.5     1      0    1     0  class2
2   15.3     2      0    0     1  class1
3   11.3     0      0    1     0  class1
4   13.2     1      0    0     1  class2

In [51]:
pd.get_dummies(df[['color']]).replace({False: 0, True: 1})

color_blue  color_green  color_red
0           0            1          0
1           0            0          1
2           1            0          0
3           0            0          1
4           1            0          0

In [52]:
df3

price  size  green  red  blue       y
0   10.1     0      1    0     0  class1
1   13.5     1      0    1     0  class2
2   15.3     2      0    0     1  class1
3   11.3     0      0    1     0  class1
4   13.2     1      0    0     1  class2

In [53]:
from sklearn.preprocessing import LabelEncoder

In [54]:
le = LabelEncoder()

In [55]:
le.fit(df['y'])

LabelEncoder()

In [57]:
le.classes_

array(['class1', 'class2'], dtype=object)

In [58]:
le.transform(df['y'])

array([0, 1, 0, 0, 1])

In [59]:
df4 = df3.copy()

In [63]:
df

price size  color       y
0   10.1    M  green  class1
1   13.5    L    red  class2
2   15.3   XL   blue  class1
3   11.3    M    red  class1
4   13.2    L   blue  class2

In [62]:
df4['y'] = le.transform(df['y'])
display(df4)

price  size  green  red  blue  y
0   10.1     0      1    0     0  0
1   13.5     1      0    1     0  1
2   15.3     2      0    0     1  0
3   11.3     0      0    1     0  0
4   13.2     1      0    0     1  1